### ISSUE TITLE
cf-spring: Could not add metadata to service plan

### ISSUE THREAD

**Issue by Joyce-yi** [cloudfoundry-community/cf-java-component#10]
According to the docu of pivotal, the metadata of plan should include something like  "costs":[{"amount":{"usd":99.0,"eur":49.0},unit":"MONTHLY"}.

This json string could not created using the current verison of cf-spring.

Affected Version 0.3

**Comment by youngm** [comment]
Thanks.  If you find the problem and can submit a PR that would be great!

**Comment by Joyce-yi** [comment]
I would like to do it :)

2015-06-09 23:54 GMT+02:00 Mike Youngstrom <notifications@github.com>:

**Comment by mheath** [comment]
I started on a fix a few days ago and just barely got the fix pushed up.

@Joyce-yi will you test my fix in the 'fix-metadata-10' branch?

**Comment by Joyce-yi** [comment]
Do it today and give you a feedback

**Comment by Joyce-yi** [comment]
It works for me, thanks :)

**Comment by mheath** [comment]
Thanks @Joyce-yi! I merged this into master.
